java: Use END_OF_FILE for NoHttpResponseException
NoHttpResponseException indicates the server unexpectedly closed the
connection.  Using an explicit error code makes it easier to handle
retries.  Example stack trace:

org.apache.thrift.transport.TTransportException: http request failed: test:8123 failed to respond
 at com.workiva.frugal.transport.FHttpTransport.makeRequest(FHttpTransport.java:266)
 at com.workiva.frugal.transport.FHttpTransport.request(FHttpTransport.java:206)
 at com.workiva.test.FTestService$InternalClient.test(FTestService.java:1)
...
Caused by: org.apache.http.NoHttpResponseException: linking-api.workiva:8123 failed to respond
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
 at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
 at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
 at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
 at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
 at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
 at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
 at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
 at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
 at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
 at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
 at com.workiva.frugal.transport.FHttpTransport.makeRequest(FHttpTransport.java:258)