java: Improve logging of response buffer overflow
Currently, the server does not log when it fails to write a response
because it has overflowed the response buffer, so the only way to detect
the condition is to look at the log of a client.  Rethrow the
application exception so that it will be logged (FBaseProcessor
otherwise discards TException), and set the cause to the underlying
transport exception for clarity, which is similar to the code generated
for an internal error.

Example output:

2019-03-12 12:32:09,712 ERROR [example-1] c.w.f.p.FBaseProcessor [FBaseProcessor.java:55] Exception occurred while processing request with correlation id fe4c673a1c9945a0b3446bd7f4e841b6
org.apache.thrift.TApplicationException: response too large: Buffer size reached (1048576)
	at com.workiva.frugal.processor.FBaseProcessor.writeApplicationException(FBaseProcessor.java:115)
	at example.v1.FExampleService$Processor.access$800(FExampleService.java:183)
	at example.v1.FExampleService$Processor$Get.process(FExampleService.java:251)
	at com.workiva.frugal.processor.FBaseProcessor.process(FBaseProcessor.java:52)
	at com.workiva.frugal.server.FNatsServer$Request.process(FNatsServer.java:328)
	at com.workiva.frugal.server.FNatsServer$Request.run(FNatsServer.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Buffer size reached (1048576)
	at com.workiva.frugal.transport.TMemoryOutputBuffer.write(TMemoryOutputBuffer.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.writeBinary(TBinaryProtocol.java:211)
	at com.workiva.frugal.protocol.FProtocol.writeBinary(FProtocol.java:209)
	at example.v1.GetResponse$GetResponseStandardScheme.write(GetResponse.java:360)
	at example.v1.GetResponse$GetResponseStandardScheme.write(GetResponse.java:323)
	at example.v1.GetResponse.write(GetResponse.java:273)
	at example.v1.FExampleService$get_result$get_resultStandardScheme.write(FExampleService.java:1074)
	at example.v1.FExampleService$get_result$get_resultStandardScheme.write(FExampleService.java:1028)
	at example.v1.FExampleService$get_result.write(FExampleService.java:967)
	at example.v1.FExampleService$Processor$Get.process(FExampleService.java:246)
	... 6 common frames omitted